services:
  - type: web
    name: cybersecurity-education-lab
    env: python
    buildCommand: pip install -r requirements.txt && python init_db.py
    startCommand: python app.py
    plan: free
    envVars:
      - key: FLASK_ENV
        value: development
      - key: FLASK_DEBUG
        value: true
      - key: PORT
        value: 10000
      - key: RENDER
        value: true
    healthCheckPath: /lab_login
